# Generated by Django 4.2.6 on 2023-10-25 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("adress", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("en_attente", "en attente"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                        ],
                        default="en_attente",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "collectpoint",
                "verbose_name_plural": "collectpoints",
            },
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[(1, "plein"), (2, "intermediaire"), (3, "vide")],
                        default=3,
                        max_length=20,
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[(1, "organique"), (2, "plastique"), (3, "radioactif")],
                        default=1,
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Container",
                "verbose_name_plural": "Containers",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Collecte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_collecte", models.DateField()),
                (
                    "collect_state",
                    models.CharField(
                        choices=[
                            ("en_attente", "en attente"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "collect_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waste.collectpoint",
                    ),
                ),
                (
                    "residents",
                    models.ManyToManyField(
                        related_name="resident_included_in_the_collect",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collecte",
                "verbose_name_plural": "Collectes",
                "db_table": "",
                "managed": True,
            },
        ),
    ]
